In [42]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, MinMaxScaler
from sklearn.model_selection import train_test_split, learning_curve
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix, precision_recall_fscore_support, precision_score, recall_score
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline


In [43]:
train_data= pd.read_csv('C:\\Users\\USER\\Downloads\\train (1).csv')
train_data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [44]:
test_data = pd.read_csv('C:\\Users\\USER\\Downloads\\test.csv')

In [45]:
train_data.drop(['Cabin', 'Ticket'], axis=1, inplace=True)
test_data.drop(['Cabin', 'Ticket'], axis=1, inplace=True)

In [46]:
train_data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch     Fare Embarked  
0      0   7.2500        S  
1      0  71.2833        C  
2      0   7.9250        S  
3      0  53.1000        S  
4      0   8.0500        S

In [48]:
test_data.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch     Fare Embarked  
0  34.5      0      0   7.8292        Q  
1  47.0      1      0   7.0000        S  
2  62.0      0      0   9.6875        Q  
3  27.0      0      0   8.6625        S  
4  22.0      1      1  12.2875        S

In [8]:
combine = [train_data, test_data]
combine
for ds in combine:
    ds['Title'] = ds.Name.str.extract(' ([A-Za-z]+)\.', expand=False)

pd.crosstab(train_data['Title'], train_data['Sex'])


Sex       female  male
Title                 
Capt           0     1
Col            0     2
Countess       1     0
Don            0     1
Dr             1     6
Jonkheer       0     1
Lady           1     0
Major          0     2
Master         0    40
Miss         182     0
Mlle           2     0
Mme            1     0
Mr             0   517
Mrs          125     0
Ms             1     0
Rev            0     6
Sir            0     1

In [49]:
train_data.drop(['PassengerId', 'Name'], axis=1, inplace=True)
test_data.drop('Name', axis=1, inplace=True)

In [50]:
train_data.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [51]:
test_data.head()

PassengerId  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0          892       3    male  34.5      0      0   7.8292        Q
1          893       3  female  47.0      1      0   7.0000        S
2          894       2    male  62.0      0      0   9.6875        Q
3          895       3    male  27.0      0      0   8.6625        S
4          896       3  female  22.0      1      1  12.2875        S

In [12]:
for ds in combine:
    ds['Sex'] = ds['Sex'].map({'female':1, 'male':0})
train_data.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare Embarked Title
0         0       3    0  22.0      1      0   7.2500        S    Mr
1         1       1    1  38.0      1      0  71.2833        C   Mrs
2         1       3    1  26.0      0      0   7.9250        S  Miss
3         1       1    1  35.0      1      0  53.1000        S   Mrs
4         0       3    0  35.0      0      0   8.0500        S    Mr

In [52]:
le = LabelEncoder().fit_transform(train_data['Sex'])
train_data['Sex'] =le



In [53]:
la = LabelEncoder().fit_transform(train_data['Embarked'])
train_data['Embarked'] =la


In [54]:
train_data.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    1  22.0      1      0   7.2500         2
1         1       1    0  38.0      1      0  71.2833         0
2         1       3    0  26.0      0      0   7.9250         2
3         1       1    0  35.0      1      0  53.1000         2
4         0       3    1  35.0      0      0   8.0500         2

In [55]:
X= train_data.drop('Survived', axis=1)

In [56]:
X

Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         3    1  22.0      1      0   7.2500         2
1         1    0  38.0      1      0  71.2833         0
2         3    0  26.0      0      0   7.9250         2
3         1    0  35.0      1      0  53.1000         2
4         3    1  35.0      0      0   8.0500         2
..      ...  ...   ...    ...    ...      ...       ...
886       2    1  27.0      0      0  13.0000         2
887       1    0  19.0      0      0  30.0000         2
888       3    0   NaN      1      2  23.4500         2
889       1    1  26.0      0      0  30.0000         0
890       3    1  32.0      0      0   7.7500         1

[891 rows x 7 columns]

In [57]:
train_data

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0           0       3    1  22.0      1      0   7.2500         2
1           1       1    0  38.0      1      0  71.2833         0
2           1       3    0  26.0      0      0   7.9250         2
3           1       1    0  35.0      1      0  53.1000         2
4           0       3    1  35.0      0      0   8.0500         2
..        ...     ...  ...   ...    ...    ...      ...       ...
886         0       2    1  27.0      0      0  13.0000         2
887         1       1    0  19.0      0      0  30.0000         2
888         0       3    0   NaN      1      2  23.4500         2
889         1       1    1  26.0      0      0  30.0000         0
890         0       3    1  32.0      0      0   7.7500         1

[891 rows x 8 columns]

In [58]:
train_data=train_data.fillna(1)
train_data.isnull().sum()


Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [59]:
X= train_data.drop('Survived', axis=1)
X.isnull().sum()

Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [60]:
y = train_data['Survived']

In [61]:
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [23]:
X.shape, y.shape

((891, 8), (891,))

# Train/Test Set

In [62]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.4, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (534, 7) (534,)
Test set: (357, 7) (357,)


## LOGISTIC REGRESSION

In [63]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LR = LogisticRegression(C=0.01, solver='liblinear').fit(X_train,y_train)
LR

LogisticRegression(C=0.01, solver='liblinear')

In [64]:
yhat = LR.predict(X_test)
yhat

array([0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,

In [65]:
yhat_prob = LR.predict_proba(X_test)
yhat_prob

array([[0.72285497, 0.27714503],
       [0.71859235, 0.28140765],
       [0.60647924, 0.39352076],
       [0.4503851 , 0.5496149 ],
       [0.69856142, 0.30143858],
       [0.58877828, 0.41122172],
       [0.51204932, 0.48795068],
       [0.601316  , 0.398684  ],
       [0.46119366, 0.53880634],
       [0.67520605, 0.32479395],
       [0.72418793, 0.27581207],
       [0.69454136, 0.30545864],
       [0.55362512, 0.44637488],
       [0.7162247 , 0.2837753 ],
       [0.43429923, 0.56570077],
       [0.64801384, 0.35198616],
       [0.72200251, 0.27799749],
       [0.60254165, 0.39745835],
       [0.72280396, 0.27719604],
       [0.54582   , 0.45418   ],
       [0.67621668, 0.32378332],
       [0.68744558, 0.31255442],
       [0.69032171, 0.30967829],
       [0.68879616, 0.31120384],
       [0.53262667, 0.46737333],
       [0.58726451, 0.41273549],
       [0.4433701 , 0.5566299 ],
       [0.31603914, 0.68396086],
       [0.72451502, 0.27548498],
       [0.72224918, 0.27775082],
       [0.

In [66]:
lr_model =  LogisticRegression(solver='liblinear')

In [67]:
LR.score(X_test, y_test)

0.7394957983193278

In [68]:
accuracy_score( y_test, yhat)

0.7394957983193278

In [69]:
def evaluate_metrics(yt, yp):
    results_pos = {}
    results_pos['accuracy'] = accuracy_score(yt, yp)
    precision, recall, f_beta, _ = precision_recall_fscore_support(yt, yp)
    results_pos['recall'] = recall
    results_pos['precision'] = precision
    results_pos['f1score'] = f_beta
    return results_pos

In [70]:
evaluate_metrics(y_test, yhat)

{'accuracy': 0.7394957983193278,
 'recall': array([0.94017094, 0.35772358]),
 'precision': array([0.73578595, 0.75862069]),
 'f1score': array([0.82551595, 0.48618785])}

In [71]:
lr=lr_model.fit(X,y)

In [72]:
lr_pre= lr.predict(X)
lr_model.score(X,y)

0.8002244668911336

## Support Vector Machine

In [86]:
from sklearn.svm import SVC

In [93]:
sv = SVC(kernel='linear')
sv

SVC(kernel='linear')

In [94]:
sv.fit(X_train, y_train)

SVC(kernel='linear')

In [98]:
sv_pred = sv.predict(X_test)
sv_pred[0:5]

array([0, 0, 1, 1, 0], dtype=int64)

In [96]:
accuracy = sv.score(X_test, y_test)
accuracy

0.8067226890756303

In [99]:
evaluate_metrics(y_test, sv_pred)

{'accuracy': 0.8067226890756303,
 'recall': array([0.87179487, 0.68292683]),
 'precision': array([0.83950617, 0.73684211]),
 'f1score': array([0.85534591, 0.70886076])}

In [103]:
from sklearn.metrics import jaccard_score
jaccard_score(y_test, sv_pred,pos_label=0)

0.7472527472527473

## Decision Tree Classifier

In [104]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_text

In [122]:
rs=123

In [127]:
dt = DecisionTreeClassifier()

In [128]:
dt.fit(X_train,y_train)

DecisionTreeClassifier()

In [129]:
dt_pred= dt.predict(X_test)


In [130]:
accuracy = dt.score(X_test, y_test)
accuracy 

0.7787114845938375

In [131]:
evaluate_metrics(y_test, dt_pred)

{'accuracy': 0.7787114845938375,
 'recall': array([0.82905983, 0.68292683]),
 'precision': array([0.83261803, 0.67741935]),
 'f1score': array([0.83083512, 0.68016194])}

In [132]:
def evaluate_metrics(yt, yp):
    results_pos = {}
    results_pos['accuracy'] = accuracy_score(yt, yp)
    precision, recall, f_beta, _ = precision_recall_fscore_support(yt, yp, average='binary')
    results_pos['recall'] = recall
    results_pos['precision'] = precision
    results_pos['f1score'] = f_beta
    return results_pos

In [133]:
evaluate_metrics(y_test, dt_pred)

{'accuracy': 0.7787114845938375,
 'recall': 0.6829268292682927,
 'precision': 0.6774193548387096,
 'f1score': 0.680161943319838}

## Random forest Classifier

In [157]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification

In [158]:
Rf = RandomForestClassifier(n_estimators = 20)
Rf.fit(X_train, y_train)

RandomForestClassifier(n_estimators=20)

In [159]:
rf= Rf.predict(X_test)
evaluate_metrics(y_test, rf)

{'accuracy': 0.8207282913165266,
 'recall': 0.6747967479674797,
 'precision': 0.7757009345794392,
 'f1score': 0.7217391304347825}

In [161]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, rf)
cm

array([[210,  24],
       [ 40,  83]], dtype=int64)

In [171]:

from sklearn.ensemble import GradientBoostingClassifier

In [172]:
xgb = GradientBoostingClassifier()

In [173]:
 xgb.fit(X_train,y_train)

GradientBoostingClassifier()

In [174]:
xg = xgb.predict(X_test)

In [175]:
accuracy= xgb.score(X_test, y_test)
accuracy

0.8291316526610645

In [176]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.datasets import make_classification
ada = AdaBoostClassifier()


In [177]:
ada.fit(X_train, y_train)

AdaBoostClassifier()

In [178]:
y_ada_pred = ada.predict(X_test)

In [179]:
accuracy = ada.score(X_test, y_test)
print(accuracy)

0.7899159663865546


In [181]:
from sklearn.naive_bayes import GaussianNB

In [182]:
NB = GaussianNB()
NB.fit(X_train, y_train)
y_nb_pred = NB.predict(X_test)

In [183]:
accuracy = NB.score(X_test, y_test)
print(accuracy)


0.8095238095238095
